### ISSUE TITLE
Calc visualizer should show the argument names from the app manifest

### ISSUE THREAD

**Issue by tmadden** [thinknode/desktop#51]

**Comment by kyleburnett** [comment]
Do you mean in the graph or the sidebar? My concern with putting them into the graph is that the labels could potentially get very long. The sidebar has limited space, too, but at least there you can either wrap or scroll when needed.

I would also need a route to look up a function definition by {account}/{app}/{name} and context id. Doable, but it doesn't exist yet.

**Comment by tmadden** [comment]
I was thinking in the graph. Maybe you could truncate them if they're too long?

I don't think you'd _need_ that new route, right? You could GET the context, figure out which version of the app you're dealing with, GET the manifest for that version, and then look up the function in there. You may need some caching, but other than that, am I missing something?

**Comment by kyleburnett** [comment]
Truncating would work I think.

Let's say that you have a branch called tmadden. You install it in your development realm and generate a context for that realm. Then you make changes to the tmadden branch. The context that you just generated now points to a detached commit for that app. So, to be precise, the context could give you a version OR a branch OR a "detached commit." I can't do anything with a detached commit unless I had a realm that allowed me to look up the function definition (via the commit, given the context). In this situation, I could fall back to "arg0", "arg1", ...

A route that allowed me to look up the function definition would actually lend itself better to caching, since the contents of a context (or, rather, the way it's represented in the JSON response) can change and the current state of a branch can change. An account/app/name and context id combination will always map to a particular function definition.

**Comment by tmadden** [comment]
Ah, I see. OK, whatever works.
