### ISSUE TITLE
Large calculation trees still hang the calculation visualizer

### ISSUE THREAD

**Issue by tmadden** [thinknode/desktop#53]
OK, I think this one's not due to my stupidity. ;-)

context: 57d6a2740040b58491e12524bece1f3b
calculation: 57e54bf90100008ee60dbe31c3cb5e84

As this loads, the UI becomes very unresponsive for me. Eventually I get "An unexpected error occurred", but it keeps loading, and if I continue to wait, the whole window goes black. I have to just kill the process.

**Comment by ewghl4jh** [comment]
Okay, I will investigate. I guess I wasn't using large enough trees for my testing.

Assuming it's the same issue, how about this: I don't download the result data for each node at the start. Instead, when you click on the node to view the details, I will show you a button that says "Fetch JSON" if the data is available and the size is less than a certain threshold. This will do the job of fetching the JSON and storing it in memory.

**Comment by kyleburnett** [comment]
Okay, I will investigate. I guess I wasn't using large enough trees for my testing.

Assuming it's the same issue, how about this: I don't download the result data for each node at the start. Instead, when you click on the node to view the details, I will show you a button that says "Fetch JSON" if the data is available and the size is less than a certain threshold. This will do the job of fetching the JSON and storing it in memory.

**Comment by tmadden** [comment]
Yeah, that sounds good.

**Comment by kyleburnett** [comment]
That graph is massive. It was trying to load more than 162,000 nodes before it crashed on me. I'm going to have to spend some more time on optimizing the loading and storage of the requests. This is a good use case though because I've never had a graph this large before.

**Comment by tmadden** [comment]
162,000 unique nodes?

**Comment by kyleburnett** [comment]
Haha. I hope not. If so, any attempt at optimizing the loading/storage of the objects probably won't work - I'd have to do some sort of lazy loading of the requests instead. Not sure how I would handle searching the requests in that case...

But I'm caching the resolved requests, so if one argument references the id abcd1234 and another argument also references the id abcd1234, I only pull the request once. So I don't think loading the requests is where the problem is. The problem is probably that I'm transforming that request into a string for searching and display purposes, so the problem is storage. Obviously, untenable in a graph this large.
